version = 1

test_patterns = ["test/**"]

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "requirements.txt"
]

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 120
